version: "3.7"
services:
  app:
    image: node
    command: sh -c "npm install && npm start"
    ports:
      - 1337:1337
    working_dir: /api
    volumes:
      - ./:/api
  cliente:
    image: node
    command: sh -c "cd ./cliente && npm install && npm start"
    ports:
      - 4200:4200
    working_dir: /cliente/src
    volumes:
      - ./:/cliente/src